# -*- coding: utf-8 -*-
"""Reto Spark - 174707.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uhXwGrx3gTXqjz5eQ3cJeNzFQ9pNjjSp
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, when
from google.colab import drive
spark = SparkSession.builder.master("local[*]").getOrCreate()
drive.mount('/content/drive')

def ejercicio():

  df = spark.read.csv('/content/drive/MyDrive/Colab Notebooks/Reto Spark/pokemon.csv', header=True, inferSchema=True)

  df_aux = df.filter(~col("Name").startswith("Mega")) \
                .filter(col("Legendary") == False) \
                .withColumn("Speed X2", col("Speed") * 2) \
                .filter(col("Speed X2") > 100) \
                .groupBy("Generation") \
                .count() \
                .orderBy("Generation") \
                .withColumnRenamed("count", "Conteo") \
                .withColumn("Conteo", col("Conteo").cast("string"))

  pandas_df = df_aux.toPandas()

  return pandas_df

ejercicio()